### ISSUE TITLE
还有超时报错的问题

### ISSUE THREAD

**Issue by acmileZZZ** [ddddhm1234/DoIPSimulator#1]
```
Traceback (most recent call last):
  File "/home/muyang/Desktop/DoIPSimulator/main.py", line 22, in <module>
    uds.open_extended_session()
  File "/home/muyang/Desktop/DoIPSimulator/doipsimu/doipclient.py", line 203, in open_extended_session
    resp = self.socket.recv()
  File "/home/muyang/.pyenv/versions/3.10.14/lib/python3.10/site-packages/scapy/contrib/automotive/doip.py", line 295, in recv
    self.buffer += self.ins.recv(8)
TimeoutError: timed out
```
首先是DoIPSocket定义的时候没有buffer这个初始量，我自己加进去了（这里我怀疑用scapy版本问题），然后就报超时，不知道如何解决

**Comment by ddddhm1234** [comment]
pip install scapy==2.5.0。刚看了下，scapy库更新到2.6.0了，使用2.5.0版本即可
